# Generated by Django 5.2.6 on 2025-09-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomclasses',
            name='name_of_class',
            field=models.CharField(max_length=40, unique=True, verbose_name='Класс комнаты'),
        ),
    ]
