# Generated by Django 5.2.6 on 2025-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contacts',
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(default='Null', max_length=40, unique=True, verbose_name='Эдектронная почта'),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(default='Null', max_length=40, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='Null', max_length=40, unique=True, verbose_name='Эдектронная почта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='Null', max_length=40, unique=True, verbose_name='Номер телефона'),
        ),
    ]
