# Generated by Django 5.2.6 on 2025-09-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_roomclasses_name_of_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomservice',
            options={'verbose_name': 'Блюдо в номер', 'verbose_name_plural': 'Блюда в номер'},
        ),
    ]
