# Generated by Django 5.2.7 on 2025-11-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_remove_clients_contacts_remove_employee_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='media/'),
        ),
    ]
