# Generated by Django 5.2.7 on 2025-11-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_dishes_image_events_image_roomclasses_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default='', verbose_name='Описание услуги'),
        ),
    ]
