# Generated by Django 5.2.6 on 2025-09-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_roomservice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='sex_id',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='sex_id',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
