# Generated by Django 5.2.7 on 2025-11-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='Dishes'),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='Events/'),
        ),
        migrations.AlterField(
            model_name='roomclasses',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='RoomClasses/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='Services/'),
        ),
    ]
