# Generated by Django 5.2.7 on 2025-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0005_alter_dishes_image_alter_events_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='Null', max_length=50, unique=True, verbose_name='Название услуги'),
        ),
    ]
