# Generated by Django 5.2.7 on 2025-11-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0006_alter_services_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='services',
            name='second_image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='Services/'),
        ),
        migrations.AddField(
            model_name='services',
            name='third_image',
            field=models.ImageField(default='static/media/Logo.svg', upload_to='Services/'),
        ),
    ]
