# Generated by Django 5.2.7 on 2025-11-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_rename_image_services_main_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='mini_description',
        ),
        migrations.AddField(
            model_name='services',
            name='end_text',
            field=models.TextField(default='', verbose_name='Конечный текст'),
        ),
        migrations.AddField(
            model_name='services',
            name='first_paragraph',
            field=models.TextField(default='', verbose_name='Первый параграф'),
        ),
        migrations.AddField(
            model_name='services',
            name='first_title',
            field=models.TextField(default='', verbose_name='Первый заголовок'),
        ),
        migrations.AddField(
            model_name='services',
            name='second_paragraph',
            field=models.TextField(default='', verbose_name='Второй параграф'),
        ),
        migrations.AddField(
            model_name='services',
            name='second_title',
            field=models.TextField(default='', verbose_name='Второй заголовок'),
        ),
        migrations.AddField(
            model_name='services',
            name='third_paragraph',
            field=models.TextField(default='', verbose_name='Третий параграф'),
        ),
        migrations.AddField(
            model_name='services',
            name='third_title',
            field=models.TextField(default='', verbose_name='Третий заголовок'),
        ),
    ]
