# Generated by Django 5.2.7 on 2025-11-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_rename_description_services_mini_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='first_title',
            field=models.CharField(default='', max_length=100, verbose_name='Первый заголовок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='second_title',
            field=models.TextField(default='', max_length=100, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='third_title',
            field=models.TextField(default='', max_length=100, verbose_name='Третий заголовок'),
        ),
    ]
