# Generated by Django 5.2.7 on 2025-11-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0009_alter_services_first_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='second_title',
            field=models.CharField(default='', max_length=100, verbose_name='Второй заголовок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='third_title',
            field=models.CharField(default='', max_length=100, verbose_name='Третий заголовок'),
        ),
    ]
