# Generated by Django 5.2.7 on 2025-11-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0010_alter_services_second_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_types', models.CharField(default='', max_length=30, verbose_name='Типы кровати')),
            ],
            options={
                'verbose_name': 'Типы кроватей',
                'verbose_name_plural': 'Типы кровати',
            },
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание комнаты'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='guests',
            field=models.IntegerField(default=0, verbose_name='Количество гостей'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='min_desc',
            field=models.TextField(default='', verbose_name='Описание карточки'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='square_meters',
            field=models.IntegerField(default=0, verbose_name='Квадратные метры'),
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='bed_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.bedtypes', verbose_name='id Типа кровати'),
        ),
    ]
