# Generated by Django 5.2.7 on 2025-11-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0011_bedtypes_roomclasses_desc_roomclasses_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomclasses',
            name='number_of_beds',
        ),
        migrations.AddField(
            model_name='roomclasses',
            name='beds',
            field=models.IntegerField(default=0, verbose_name='Количество кроватей'),
        ),
        migrations.AlterField(
            model_name='roomclasses',
            name='guests',
            field=models.IntegerField(verbose_name='Количество гостей'),
        ),
    ]
